# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ed545dd3d592ece9c195d3a8b84d6ded"
name = "modera-fashion-app"
handle = "modera-fashion-app"
application_url = "https://localhost:57680"
embedded = true
distribution_public = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://localhost:57680/auth/callback",
  "https://localhost:57680/auth/shopify/callback",
  "https://localhost:57680/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
